### ISSUE TITLE
wasmparser: Missing options in WasmFeatures

### ISSUE THREAD

**Issue by Robbepop** [bytecodealliance/wasm-tools#481]
Currently the [`WasmFeatures struct`](https://docs.rs/wasmparser/0.82.0/wasmparser/struct.WasmFeatures.html) in the `wasmparser` crate has many options for controlling single Wasm proposal implementations.
However, some Wasm proposals such as `nontrapping-float-to-int-instructions`, `sign-extension-ops` and `mutable-global` are missing from there.

Is this intentional? If yes, what is the reason?

If not, would the authors of the `wasmparser` crate like to receive PRs to add those configuration options so that `wasmparser` can be used to validate against Wasm inputs making use of those features?

## Motivation

For some use cases it might be very important to guard against usage of certain unsupported Wasm proposals. An example for this is in the context where Wasm instructions are metered and there is no defined metering for certain instructions of Wasm proposals.

## ToDo

- [ ] Add `mutable_global: bool` field to `WasmFeatures` to enable or disable the `mutable-global` Wasm proposal.
- [ ] Add `nontrapping_float_to_int_instructions: bool` field to `WasmFeatures` to enable or disable the `nontrapping-float-to-int-instructions` Wasm proposal.
- [ ] Add `sign_extension_ops: bool` field to `WasmFeatures` to enable or disable the `sign-extension-ops` Wasm proposal.

**Comment by alexcrichton** [comment]
I think this is mostly because those proposals were largely stable before they were added here, but it should be fine to retroactively add them if necessary.

**Comment by Robbepop** [comment]
Okay, add some TODOs to the initial comment and am looking to tackle this.
